# Install dependencies
FROM node:16 AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# We need to use Ubuntu in order to install Watchman
FROM node:16 as dev

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
