# Install dependencies
FROM node:16 AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# We need to use Ubuntu in order to install Watchman
FROM ubuntu:20.04 as dev

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Install Node
RUN set -uex; \
    apt-get update; \
    apt-get install -y ca-certificates curl gnupg; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    NODE_MAJOR=16; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get update; \
    apt-get install nodejs -y;

# Install Watchman
RUN apt-get -y install wget && \
    wget -O watchman.deb https://github.com/facebook/watchman/releases/download/v2023.09.04.00/watchman_ubuntu20.04_v2023.09.04.00.deb && \
    apt-get -y install ./watchman.deb
