GET http://localhost:3000/api/user/announcement
Content-Type: application/json
accesstoken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVkMzQwZGRiYzNjNWJhY2M0Y2VlMWZiOWQxNmU5ODM3ZWM2MTYzZWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaGVhbGluZzRoZXJvZXMtZjFiYmIiLCJhdWQiOiJoZWFsaW5nNGhlcm9lcy1mMWJiYiIsImF1dGhfdGltZSI6MTY2NTkxMzk1MCwidXNlcl9pZCI6ImFvTE9BelZNeE5aWXAzazdIZU1VT0hwVWF2NTMiLCJzdWIiOiJhb0xPQXpWTXhOWllwM2s3SGVNVU9IcFVhdjUzIiwiaWF0IjoxNjY1OTEzOTUwLCJleHAiOjE2NjU5MTc1NTAsImVtYWlsIjoidGVzdGluZ0BleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0aW5nQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.qN5UHZnxELCNU1-riAatXDLK7xCAEhTjrmP-vc-biiM0g5SNHaWtjqUsH_MESLTV1ytfppoNxCOboKCdncdusnr_uAO87IA1TZGobgJO3AINoJNT6j8XFU_ny5uUu49QlCzSU2N3E803QlHP2NsPd38qDk0o6qK_Gv133on9dl72RD6vs8HHZggWHJCzoUgkCDZaXBsXxjGl4FUWPZUpoen3mcV15XlS7csdTRhsfoxy-LrXC-qZ-TINSX8ReB2QcJwEgtjWQsEoFF3hWdIKJAmXp5wD38oSER38w7kAudHj4ty7KMBO-_-O-H2yNRUzGqnpbox3l6zXTElZnnm8kg