// Note these can be exposed
const FIREBASE_API_KEY = "AIzaSyD0uycogTnN_MEO6cKp0WEnGApVuKOFyys";
const FIREBASE_AUTH_DOMAIN = "healing4heroes-f1bbb.firebaseapp.com";
const FIREBASE_PROJECT_ID = "healing4heroes-f1bbb";
const FIREBASE_STORAGE_BUCKET = "healing4heroes-f1bbb.appspot.com";
const FIREBASE_MESSAGING_SENDER_ID = "873081765798";
const FIREBASE_APP_ID = "1:873081765798:web:9e5869ae76832d28bc1967";

export {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
};
