name: lint mobile
# On pull request, make a deployment to Preview
# On merge into main, make a deployment to Develop
# On merge into prod, flag prod, make a deployment to Production
on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mobile
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}

      - name: Lint files and run type-checks
        run: yarn lint
        working-directory: ${{ env.working-directory }}